_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 10
DATASETS:
  TRAIN: ("ruod_train", "brackish_train",)
  TEST: ("ruod_val", "brackish_val")
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
SOLVER:
  STEPS: (999,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 100
OUTPUT_DIR: "output/ruod_brackish/brackish_oracle_strongaug_ema/"
